name: Native-ARM64-cleanup

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  setup-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Terraform Cloud Workspace Init
        run: |
          curl -X POST https://api.github.com/repos/bbqwednesday/terraform-cloud/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "destroy '"$GITHUB_REPOSITORY"' dynamic-tf-oci-arm64-runner", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'